export const copy = {
  appName: 'סיקרט',
  tagline: 'חיים בלי סודות.',

  resonanceYours: 'התהודה שלך',
  resonancePeer: 'תהודת הזר',
  resonance: 'תהודה',

  secretsToday: 'סודות היום',
  secretsLeft: (n: number) => `נשארו ${n} סודות`,

  homeHint:
    'מתוודים על סוד, מקבלים סוד זר בתמורה. הסוד נשלח רק כשיש סוד בתמורה. טקסט בלבד.',
  newSecret: 'סוד חדש',
  continueSecret: 'המשך סוד פעיל',
  howItWorks: 'איך זה עובד?',

  intentionTitle: 'מה תרצה לשתף?',
  intentionHint: 'כיוון בלבד — לא התוכן. עוזר להתאים סוד לזר.',

  composeTitle: 'הסוד שלך',
  composeHint:
    'הזר יראה רק את הטקסט. אל תכלול שם, טלפון או @username. מינימום 100 תווים.',
  composePlaceholder: 'כתוב כאן מה שאתה רוצה לוודות...',

  sendTitle: 'שליחת הסוד',
  sendHint:
    'הסוד נשלח ומרחף בדרך אל זר. כשיגיע אליך סוד ממישהו אחר — תוכלו לקרוא את שניכם.',
  sendWarn: 'אחרי השליחה אין עריכה וביטול. אל תכלול פרטים מזהים.',
  sendCta: 'שלח וחפש סוד זר',

  queueTitle: 'מחפשים סוד בתמורה...',
  queueHint:
    'הסוד שלך מרחף בחיפוש אחר זר. כשיגיע סוד בתמורה — תיפתח הקבלה. בטא: סוד אנונימי תוך כמה שניות.',
  queueJoining: 'מעירים את השרת ושולחים לתור...',
  queueWaking: 'השרת מתעורר, רגע...',
  queueWaiting: 'מחפש סוד זר...',
  leaveQueue: 'יציאה מהתור',

  swapLoading: 'טוען סוד...',
  swapPreparing: 'מכינים את הקבלה...',
  swapFrom: (alias: string) => `סוד מ${alias}`,
  swapYourSecretFeedback: (label: string) =>
    label ? `מי שקרא את הסוד שלך — ${label}` : 'מי שקרא את הסוד שלך — עדיין לא הגיב',
  swapRateQuestion: 'איך הסוד שקראת?',
  finishNoRate: 'סיום בלי דירוג',

  revealTitle: 'משהו נחזר אליך',
  revealResonance: (v: number, delta: string) => `התהודה שלך: ${v.toFixed(1)} (${delta})`,
  revealWaiting: 'מי שקרא את הסוד שלך — עדיין לא הגיב.',
  revealPeer: (v: number) => `תהודת הזר כעת: ${v.toFixed(1)}`,
  revealContinue: 'ממשיך',

  feedbackTouched: 'נגע בי',
  feedbackDishonest: 'לא כנה',
  feedbackReport: 'דיווח',
  hideFromScreen: 'הסר מהמסך',
  reportConfirmTitle: 'דיווח על תוכן',
  reportConfirmBody: 'הדיווח נשלח והתוכן הוסר מהמסך. נבדוק תוך 24 שעות.',
  contentRemoved: 'התוכן הוסר מהמסך.',
  termsTitle: 'תנאים וכללי קהילה',
  termsSubtitle: 'יש לאשר לפני שליחה או קריאת סודות.',
  termsAgree: 'אני מסכים/ה',
  supportTitle: 'תמיכה ודיווח',
  supportIntro: 'לדיווח על תוכן פוגעני, שימוש לרעה או בעיה טכנית — פנה אלינו.',
  supportEmailLabel: 'דוא"ל',
  supportReportExplain:
    'ניתן לדווח על סוד שקיבלת ישירות ממסך הקבלה. ניתן גם להסיר סוד מהמסך בלי דיווח. אנו בודקים דיווחים תוך 24 שעות.',
  supportViewTerms: 'צפייה בתנאים המלאים',
  supportBack: 'חזרה',
  supportLink: 'תמיכה ודיווח',
  bannedTitle: 'חשבון חסום',
  bannedBody: 'החשבון נחסם בשל הפרת כללי הקהילה. לפנייה: office@tgbc.co.il',
  suspendedTitle: 'החשבון הושעה זמנית',
  suspendedBody: 'בגלל דיווחים או שימוש שלא לפי כללי הקהילה.',
  suspendedUntil: (when: string) => `עד: ${when}`,
  quotaExhausted: 'הגעת למכסה היומית. חוזר בחצות (שעון ישראל).',
  quotaFirstDay: 'בימים הראשונים מותרים 2 סודות ביום.',
  networkError: 'אין חיבור לשרת. נסה שוב בעוד רגע.',
  serverWaking: 'השרת מתעורר, רגע...',
  retry: 'נסה שוב',
  loadingProfile: 'טוען...',
  onboardingSlide2Title: 'וידוי וקבלה',
  onboardingSlide2Body: 'מתוודים על סוד, מקבלים סוד זר בתמורה. בלי שם. בלי חזרה.',
  onboardingSlide3Title: 'לא טיפול',
  onboardingSlide3Body: 'אם אתה במצב קשה — פנה לעזרה מקצועית. כאן מקום לשתף, לא לטפל.',
  ageConfirm: 'אני מעל גיל 18 ומבין/ה שזה לא שירות טיפולי.',
  ageConfirmRequired: 'יש לאשר גיל 18+ כדי להמשיך.',
  termsScrollHint: 'גלול עד הסוף לפני האישור.',
  botHint: 'בטא: אם אין זר זמין, תקבל סוד אנונימי תוך כמה שניות.',
  composeBackWarn: 'לצאת בלי לשלוח? הטיוטה נשמרת במכשיר.',
  swapError: 'לא הצלחנו לטעון את הסוד.',
  swapInvalid: 'החלפה לא נמצאה.',
  mailtoFailed: 'לא ניתן לפתוח דוא״ל. כתוב ל: office@tgbc.co.il',
};
